# Site settings
name: Frank's Blog
email: frankxjkuang@gmail.com
author: Frank·J
url: https://www.kuangxj.eu.org/
# 个人简历
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/frankxjkuang/
baseurl: ""
description: This too shall pass!
meta_description: Frank;个人博客;学习;web;
motto: The safest way to try to get what you want is to try to deserve what you want

banner: Do what you want to do and start now

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: frankxjkuang
highlighter: Pygments

# Build settings
markdown: kramdown
# 直接写在百度统计里，这个配置可以不用了
baidu_analysis: e2e60863afcb2e6d5e0598e66a924eaf

